#!/usr/bin/env fish

if [ (count $argv) -lt 1 ]
    set argv[1] "last"
end

switch $argv[1]
    case "pop"
        echo '"'(tail -n1 $HOME/tasks)'" is done'
        sed '$ d' $HOME/tasks > /tmp/tasks
        mv /tmp/tasks $HOME/tasks
    case "last"
        if [ -e $HOME/tasks ]
            tail -n1 $HOME/tasks
        end
    case "count"
        if [ -e $HOME/tasks ]
            wc -l $HOME/tasks | cut -d " " -f1
        else
            echo 0
        end
    case "--help"
        echo "stack [pop|last|count]"
        echo "stack (task description)"
    case '*'
        echo $argv >> $HOME/tasks
end
exit 0
